
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    build:
      context: .
    depends_on:
      - redis
    ports:
      - 5000:5000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6123
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
  volumes:
      - ./prod-data/:data/
